### ISSUE TITLE
0.16 - Exception 'ResultSet is closed' is thrown for PageResult from createPageQuery used in a mapper

### ISSUE THREAD

**Issue by forszpanen** [1000kit/tkit-quarkus#76]
There is a problem when PageResult is used in a mapper and EntityXYXDto has a list with some data from a joined table. Explicite added Transaction works but it works different compare to Quarkus 1.x with tkit-JPA plugins. Have you encountered similar behaviour? 
```java	

public class EntityXYXDto {
    private String name1;
    private String name3;
    private List<JoinedData> JoinedData;
}


public class XYZPageResultDto extends PageResultDTO<EntityXYXDto> {
}


//controller
XYZPageResultDto pageResultDto = mapper.mapDto(service.findBySearchCriteriaPagedXYZ(searchCriteriaDto));

//service
public PageResult<EntityXYZ> findBySearchCriteriaPagedXYZ(SearchCriteriaDto dto) {
    return dao.findBySearchCriteriaPagedXYZ(dto);
}
//dao
public PageResult<EntityXYZ> findBySearchCriteriaPagedXYZ(dto) {
    CriteriaBuilder cb = this.em.getCriteriaBuilder();
    //...				 
    return createPageQuery(cq, Page.of(dto.getPageNumber(), dto.getPageSize())).getPageResult();
}
```

`2023-07-24 14:59:44,542 ERROR [XYZController] (executor-thread-0) Before mapper:
2023-07-24 14:59:44,543 WARN  [org.tki.qua.jpa.dao.PagedQuery] (executor-thread-0) Paged query used without explicit orderBy. Ordering of results between pages not guaranteed. Please add an orderBy clause to your query.
2023-07-24 14:59:44,543 WARN  [org.tki.qua.jpa.dao.PagedQuery] (executor-thread-0) Default sorting by 'id' attribute is added.
2023-07-24 14:59:44,548 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) SQL Error: 0, SQLState: null
2023-07-24 14:59:44,548 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) ResultSet is closed`

**Comment by andrejpetras** [comment]
@forszpanen example project where we can reproduce this issue would be good. PR to fix this issue is welcome.

**Comment by bartosz-kowalski-capgemini** [comment]
Hi, I have just created a new quarkus project that reproduces this issue. Please consider updating database information and add at least 1 row to each table. 

https://gitlab.com/bartosz.kowalski.capgemini/resultset

![image](https://github.com/1000kit/tkit-quarkus/assets/87004063/ae9721c3-d878-4897-9817-730a837283eb)
![image](https://github.com/1000kit/tkit-quarkus/assets/87004063/e05eec05-3ec6-4b4d-908e-a3cdd398f7e6)
![image](https://github.com/1000kit/tkit-quarkus/assets/87004063/be74ee53-cf1a-4cd1-aec0-2316e563cdf4)

**Comment by andrejpetras** [comment]
@bartosz-kowalski-capgemini this is not an issue of `PageResult`
You have parent-child (child is lazy) model which is directly use in the rest-controller.
In your case, Jackson will try to use `getChildren` method, but the children are not loaded, and the database transaction is close.
